package com.dandan.crm.workbench.mapper;

import com.dandan.crm.workbench.domain.Clue;
import com.dandan.crm.workbench.domain.Customer;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Mapper
public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Mon Dec 06 17:23:21 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Mon Dec 06 17:23:21 CST 2021
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Mon Dec 06 17:23:21 CST 2021
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Mon Dec 06 17:23:21 CST 2021
     */
    Customer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Mon Dec 06 17:23:21 CST 2021
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Mon Dec 06 17:23:21 CST 2021
     */
    int updateByPrimaryKey(Customer record);

    /**
     * 把线索中有关公司的信息转换到客户表中
     * @param customer
     * @return
     */
    int saveCustomerInformationForClueCompanyInfromation(Customer customer);
}